# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a40784144b49c5319dd2c791a271b326a388dc1d8829f0e38178864c46de80ade2b4f7963348da84d13abd7d8d426c9df40dcd2bd4aa6fca78577ec76a943175

test:
  secret_key_base: 133238462b0761e536bbab0decd29986910b7db0648752931c06a32ec278c743a7de000660fa9c40b82c05313e6b2590101096a54a89c21a95afeb4a32bd8296

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
